### ISSUE TITLE
Why backslashe is ignored ?

### ISSUE THREAD

**Issue by quentinsup** [gagle/node-properties#4]
Hello,
First, congratulation for you work !

I use you plugin for my own development and asked to myself why the backslash is ignored by your parser ? (it means 'C:\dir\file' will do 'C:dirfile').

You guess i'm working on windows where backslashes are used into paths ;)

**Comment by gagle** [comment]
Because backslashes are used to escape special characters like `\n`, `\r`, `\t`, etc. If you prepend a backslash with a regular character, i.e. `\a`, it will remove that `\`, so you get the `a` character. If you want to maintain the backslahes you need to prepend the backslash.... with another backslash: `\\`:

``` text
my_dir C:\\dir\\file
```

But you don't need to do this. On Windows you can use slashes and backslashes. This also works:

``` text
my_dir C:/dir/file
```

**Comment by quentinsup** [comment]
Thanks for you response,

That's what i'm actually doing :), but to my mind it would be possible to distinguish "\" char  alone from special chars (for example, do not interprate '\' when it is used into double quotes ?).

**Comment by gagle** [comment]
No, I can't do that. It's not in the specification.

**Comment by quentinsup** [comment]
All rights, you convinced me

Thks
