### ISSUE TITLE
parsing vmware vmx file with namespaces breaks when there are empty values

### ISSUE THREAD

**Issue by phaus** [gagle/node-properties#6]
/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:114
    p[n[n.length - 1]] = value;
                       ^
TypeError: Cannot set property 'device0' of undefined
    at namespace (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:114:21)
    at line (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:266:6)
    at Object.handlers.line (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:330:4)
    at line (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/parse.js:49:13)
    at module.exports (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/parse.js:265:5)
    at build (/Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:338:2)
    at /Users/philipp/GIT/vmrun.js/node_modules/properties/lib/read.js:418:5
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

File see https://gist.github.com/phaus/7835514

**Comment by gagle** [comment]
This is the expected behaviour. It fails because it has an incorrect namespace chain. Look at these lines:

```
usb_xhci:3.parent = "-1"
usb_xhci.autoConnect.device0 = ""
```

These are the same as:

```
usb_xhci = 3.parent = "-1"
usb_xhci.autoConnect.device0 = ""
```

More clear:

```
a = 1
a.b = 2
```

If `a` has a value you cannot nest subkeys, in this case `b`.

I've released a new version. Now instead of failing it returns an error similar to this:

```
[Error: Invalid namespace chain, the key must contain an object: usb_xhci.autoConnect.device0]
```

In your case, because you cannot modify the file to fix the error, you must use at least these options:

```
var options = {
    namespaces: true,
    separators: "=",
    strict: true
};
```

This will use only the token `=` as a separator. Note that `:` is a valid separator token in the .properties specification.

This is what it returns (you should do something with these surrounding quote chars, you could use the `reviver` option):

```
{
  'usb_xhci:4': {
    present: '"TRUE"'
  },
  usb_xhci: {
    autoConnect: {
      device0: '""'
    }
  }
}
```

**Comment by phaus** [comment]
hey... thanx a lot for the fix. i aready started to use a reviver but need some more read :-). It is working now.
